schedules:
- cron: "0 11 * * *"
  displayName: "Daily Morning Warm-up (7 AM EST)"
  branches:
    include:
    - main
  always: true # This key ensures that the scheduled pipeline will trigger even if there have been no new commits or code changes since the last run. 
  #It's useful for jobs that need to run at a scheduled frequency regardless of repository activity 
  #(such as health checks, reporting, or warming up production resources).

trigger:
  branches:
    include:
    - main

pool:
  name: 'MyLocalLaptop'
  #  vmImage: 'ubuntu-latest' # Azure Cloud machine to run the job

variables:
- group: 'Portfolio-Secrets'
# New public path that bypasses "Access is denied" errors
- name: pythonExe
  value: 'C:\\Python312\\python.exe'

steps:
  - checkout: self
    clean: true

  - script: |
      "$(pythonExe)" -m pip install --upgrade pip
      if exist requirements.txt (
          "$(pythonExe)" -m pip install -r requirements.txt
      )
    displayName: 'Install dependencies'

  - script: |
      "$(pythonExe)" monitor_portfolio.py
    env:
      SLACK_TOKEN: $(SLACK_TOKEN)
      PYTHONUTF8: 1
    displayName: 'Run Portfolio Monitor'